services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0

volumes:
  postgres_data:
